# warren — shared helpers. POSIX-ish; works under bash and zsh, macOS and Linux.
#
# A script sources this AFTER setting WARREN_ROOT, e.g.:
#   SELF="$(cd "$(dirname "$0")" && pwd)"
#   WARREN_ROOT="$(cd "$SELF/../.." && pwd)"   # depth depends on script location
#   . "$WARREN_ROOT/core/lib/warren.sh"

# --- config (generated by bootstrap; safe defaults if missing) ---
[ -f "$WARREN_ROOT/warren.config" ] && . "$WARREN_ROOT/warren.config"
: "${VAULT_PATH:=$WARREN_ROOT/vault}"
: "${MODEL:=sonnet[1m]}"

AGENTS_CONF="$WARREN_ROOT/agents.conf"
CREDS_DIR="$WARREN_ROOT/config/credentials"
BUS_TO="$VAULT_PATH/bus/to"        # per-agent inboxes (personal data → gitignored vault)
BUS_SENT="$VAULT_PATH/bus/sent"    # processed archive
CHECK_INBOX="$WARREN_ROOT/core/bus/check-inbox.sh"

# --- platform ---
warren_os() {
  case "$(uname -s)" in
    Darwin) echo macos ;;
    Linux)  echo linux ;;
    *)      echo unknown ;;
  esac
}

# --- telegram notify (best-effort; never fails the caller) ---
notify_telegram() {
  [ "${TELEGRAM_ENABLED:-0}" = "1" ] || return 0
  local text="$1" creds="$CREDS_DIR/telegram-bot.md" token chat
  [ -f "$creds" ] || return 0
  token=$(grep '^token:'   "$creds" | awk '{print $2}')
  chat=$(grep  '^chat_id:' "$creds" | awk '{print $2}')
  [ -z "$token" ] && return 0
  curl -s -X POST "https://api.telegram.org/bot${token}/sendMessage" \
    --data-urlencode "chat_id=${chat}" \
    --data-urlencode "text=${text}" >/dev/null 2>&1 || true
}

# --- iterate agents.conf: runs `cb key name dir` per non-comment line ---
# agents.conf columns:  tmux_key  AgentName  working_dir(relative to vault, "." = root)
warren_each_agent() {
  local cb="$1" key name dir _rest
  [ -f "$AGENTS_CONF" ] || return 0
  while read -r key name dir _rest; do
    case "$key" in ''|\#*) continue ;; esac
    "$cb" "$key" "$name" "$dir"
  done < "$AGENTS_CONF"
}

# lowercase helper (bus inbox folder = lowercased agent name)
warren_lc() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }
